export const GOOGLE_CALENDAR_CONFIG = {
  SERVICE_ACCOUNT_EMAIL: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
  CALENDAR_ID: process.env.NEXT_PUBLIC_GOOGLE_CALENDAR_ID
} as const;